## Work with the data generated by HurrSingleStorm.R
library("tidyverse")
rising_need_data <- read_csv("studyData/singlestormResults/risingNeed.csv") %>%
    select(-X1)
sq_data <- read_csv("studyData/singlestormResults/statusQuo.csv") %>%
    select(-X1)
all_ss_data <- read_csv("studyData/singlestormResults/allData.csv") %>%
    select(-X1)

## plot with columns of status quo and stakeholder input, rows
## of storm strength.

single_storm_by_strength <- ggplot(all_ss_data,
                                   aes(Infrastructure,
                                       ExtendedIntegralResilience)) +
    geom_boxplot() +
    facet_grid(Strongest_Storm ~ Need_Profile)




















