## Work with the data generated by HurrSingleStorm.R
library("tidyverse")
rising_need_data <- read_csv("studyData/singlestormResults/risingNeed.csv") %>%
    select(-X1) %>%
    mutate(Strongest_Storm = as.factor(Strongest_Storm))
sq_data <- read_csv("studyData/singlestormResults/statusQuo.csv") %>%
    select(-X1)%>%
    mutate(Strongest_Storm = as.factor(Strongest_Storm))
all_ss_data <- read_csv("studyData/singlestormResults/allData.csv") %>%
    select(-X1) %>%
    mutate(Strongest_Storm = as.factor(Strongest_Storm))


one_run <- read_csv("studyData/singlestormResults/one_run.csv") %>%
    select(-X1)%>%
    mutate(Strongest_Storm = as.factor(Strongest_Storm))

ts_data <- read_csv("studyData/singlestormResults/perfNeedtrajectories.csv") %>%
    select(-X1) %>%
    spread(Need_Profile, Need) %>%
    gather(Profile, Output, -Run, -Time, -Infrastructure)

ts_th <-
    ts_data %>%
    group_by(Need_Profile) %>%
    summarise(Time_Horizon = max(Time))

## plot with columns of status quo and stakeholder input, rows
## of storm strength.

single_storm_by_strength <- ggplot(all_ss_data) +
    geom_boxplot(mapping = aes(x = Infrastructure,
                               y = ExtendedIntegralResilience,
                               fill = Strongest_Storm),
                 position = position_dodge(width = .6)) +
    scale_colour_manual(c("grey90", "grey70", "grey50", "grey30")) +
    facet_wrap(~ Need_Profile, ncol = 1) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = -90,
                                        vjust = 1,
                                     hjust = 0))

single_storm_by_inf <- ggplot(all_ss_data) +
    geom_boxplot(mapping = aes(Infrastructure, ExtendedIntegralResilience)) +
    facet_wrap(~ Need_Profile, ncol = 1) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = -90,
                                        vjust = 1,
                                     hjust = 0))


SQ_vs_SN_Time <-
    ggplot(one_run, aes(Infrastructure,
                        ExtendedIntegralResilience,
                        fill = Need_Profile)) +
    geom_col(position = position_dodge())


ts_plot <- ggplot(ts_data) +
    geom_line(aes(Time,
                  Output,
                  group = Profile,
                  linetype = Profile)) +
    geom_vline(aes(xintercept = Time_Horizon),
               data = ts_th,
               color = "grey50",
               alpha = 0.5) +
    scale_linetype_manual(values = c("solid", "dotted", "dashed")) +
    geom_text(aes(x = Time_Horizon,
                  y = .1,
                  label = Need_Profile),
              data = ts_th) +
    facet_wrap(~ Infrastructure, ncol = 2) +
    theme_bw()



















